create database htht;
use htht;

CREATE TABLE `product` (
  `pid` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `pname` VARCHAR(255) CHARACTER SET utf8 DEFAULT '',
  `pdesc` TEXT CHARACTER SET utf8,
  `pimage` VARCHAR(255) CHARACTER SET utf8 DEFAULT '',
  `porder` INT(5) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;


CREATE TABLE `news` (
  `id` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `type` int(2) NOT NULL,
  `title` varchar(255) CHARACTER SET utf8 DEFAULT '',
  `content` text CHARACTER SET utf8,
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;


CREATE TABLE `message` (
  `id` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` varchar(20) CHARACTER SET utf8 DEFAULT '',
  `mobile` varchar(50) CHARACTER SET utf8 DEFAULT '',
  `content` text CHARACTER SET utf8,
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;